name: Run Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Cython extensions
      run: |
        python setup.py build_ext --inplace

    - name: Run tests
      run: |
        pip install pytest pytest-cov
        pytest Tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      continue-on-error: true

    - name: Upload coverage results to Codecov.io
      uses: codecov/codecov-action@v2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        version: "v0.1.15"

    - name: Generate coverage report
      run: |
        pip install coverage
        coverage xml

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.2.3
